name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Spotless check
      run: mvn spotless:check

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mvn failsafe:integration-test

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
